#!/bin/sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

JAVA_CMD="java"
if ! [ -x "$(command -v drip)" ]; then
  JAVA_CMD="drip" 
fi

$JAVA_CMD -jar target/scala-2.13/datr.scala-assembly-*.jar $@
